import io, sys, os

HTML = 'www/index.html'
if not os.path.exists(HTML):
    print("ERROR: index.html not found"); sys.exit(1)

with io.open(HTML, 'r', encoding='utf-8') as f:
    html = f.read()

if "__SUGS_V3__" in html:
    print("Already expanded. Exiting.")
    sys.exit(0)

# Locate the var pool = [ ... ]; inside exRenderSuggestions
start_fn = html.find("function exRenderSuggestions")
if start_fn == -1:
    print("ERROR: exRenderSuggestions not found"); sys.exit(1)

pool_start = html.find("var pool = [", start_fn)
if pool_start == -1:
    print("ERROR: var pool = [ not found"); sys.exit(1)

pool_end = html.find("];", pool_start)
if pool_end == -1:
    print("ERROR: closing ]; not found"); sys.exit(1)
pool_end += 2

NEW_POOL = '''var pool = [ /* __SUGS_V3__ */
    /* --- SOAPS & CLEANERS --- */
    "how do I make liquid soap?",
    "how do I make bar soap?",
    "how do I make black soap?",
    "how do I make neem soap?",
    "how do I make herbal soap?",
    "how do I make aloe vera soap?",
    "how do I make charcoal soap?",
    "how do I make turmeric soap?",
    "how do I make eucalyptus soap?",
    "how do I make detergent powder?",
    "how do I make bleach?",
    "how do I make toilet cleaner?",
    "how do I make floor cleaner?",
    "how do I make dish soap?",
    "how do I make dishwashing liquid?",
    "how do I make air freshener?",
    "how do I make hand wash?",
    "how do I make glass cleaner?",
    "how do I make stain remover?",
    "how do I make fabric softener?",
    "how do I make laundry starch?",
    "how do I make toilet block?",
    "how do I make oven cleaner?",
    "how do I make multipurpose cleaner?",
    "how do I make shampoo?",
    "how do I make body wash?",
    "how do I make hand sanitizer?",
    /* --- CANDLES & FUEL --- */
    "how do I make candles?",
    "how do I make beeswax candles?",
    "how do I make charcoal briquettes?",
    "how do I make sawdust briquettes?",
    "how do I make coconut shell charcoal?",
    "how do I make banana peel briquettes?",
    "how do I make bamboo charcoal?",
    "how do I make rice husk briquettes?",
    /* --- BEEKEEPING --- */
    "how do I start bee farming?",
    "how do I start stingless bee farming?",
    "how do I make beehive?",
    "how do I make bee pollen?",
    "how do I make propolis?",
    "how do I make beeswax lip balm?",
    "how do I make beeswax food wraps?",
    "how do I make royal jelly?",
    /* --- FARMING --- */
    "how do I start cricket farming?",
    "how do I start BSF farming?",
    "how do I start mealworm farming?",
    "how do I grow mushrooms?",
    "how do I grow oyster mushrooms?",
    "how do I farm snail?",
    "how do I farm earthworms?",
    "how do I make vermicompost?",
    "how do I farm quail?",
    "how do I farm rabbit?",
    "how do I farm kienyeji chicken?",
    "how do I farm tilapia?",
    "how do I farm catfish?",
    "how do I farm duck?",
    "how do I farm turkey?",
    "how do I farm goat?",
    "how do I farm pig?",
    "how do I grow azolla?",
    "how do I grow duckweed?",
    "how do I grow hydroponic fodder?",
    "how do I grow microgreens?",
    "how do I grow moringa?",
    "how do I grow tomatoes?",
    "how do I grow onions?",
    "how do I grow cabbage?",
    "how do I grow carrots?",
    "how do I grow pepper?",
    "how do I grow maize?",
    "how do I grow beans?",
    "how do I grow bananas?",
    /* --- AGRICULTURE INPUTS --- */
    "how do I make compost?",
    "how do I make bone meal?",
    "how do I make fish waste fertilizer?",
    "how do I make seaweed fertilizer?",
    "how do I make banana liquid fertilizer?",
    "how do I make BSF frass?",
    "how do I make neem pesticide?",
    "how do I make tephrosia pesticide?",
    "how do I make wood ash pesticide?",
    "how do I make chilli garlic pesticide?",
    "how do I make african basil pesticide?",
    "how do I make soil pH meter?",
    "how do I make seedling nursery?",
    /* --- FOOD & SNACKS --- */
    "how do I make peanut butter?",
    "how do I make honey?",
    "how do I make fruit jam?",
    "how do I make tomato sauce?",
    "how do I make chilli sauce?",
    "how do I make yoghurt?",
    "how do I make cheese?",
    "how do I make ice cream?",
    "how do I make chocolate?",
    "how do I make coffee?",
    "how do I make tea packaging?",
    "how do I make spice blends?",
    "how do I make bread?",
    "how do I make cakes?",
    "how do I make cupcakes?",
    "how do I make muffins?",
    "how do I make cookies?",
    "how do I make brownies?",
    "how do I make cake pops?",
    "how do I make cheesecake?",
    "how do I make red velvet cake?",
    "how do I make black forest cake?",
    "how do I make carrot cake?",
    "how do I make banana cake?",
    "how do I make pineapple cake?",
    "how do I make apple pie?",
    "how do I make fruit tart?",
    "how do I make samosa?",
    "how do I make chapati?",
    "how do I make rolex?",
    "how do I make mandazi?",
    "how do I make doughnuts?",
    "how do I make popcorn?",
    "how do I make chips?",
    "how do I make chips mayai?",
    "how do I make meatballs?",
    "how do I make corn dogs?",
    "how do I make empanadas?",
    "how do I make samosa cheese?",
    "how do I make samosa chicken?",
    "how do I make samosa vegetable?",
    "how do I make meat pie?",
    "how do I make mushroom pie?",
    "how do I make vegetable pie?",
    "how do I make beef pie?",
    "how do I make sausage rolls?",
    "how do I make chicken rolls?",
    "how do I make cheese straws?",
    "how do I make cheese balls?",
    "how do I make fish fingers?",
    "how do I make potato croquettes?",
    "how do I make chicken nuggets?",
    "how do I make fish balls?",
    "how do I make yam chips?",
    "how do I make potato wedges?",
    "how do I make roasted maize?",
    "how do I make roasted cassava?",
    "how do I make fried cassava chips?",
    "how do I make roasted chicken?",
    "how do I make muchomo?",
    "how do I make matoke?",
    "how do I make fish stew?",
    "how do I make chicken stew?",
    "how do I make coconut rice?",
    "how do I make pilau?",
    "how do I make biryani?",
    "how do I make kikomando?",
    "how do I make chapati beans?",
    "how do I make fried liver?",
    "how do I make liver and chips?",
    "how do I make fried gizzard?",
    "how do I make grilled pork?",
    "how do I make smokies?",
    "how do I make passion juice?",
    "how do I make ice lollipops?",
    "how do I make toffee candy?",
    "how do I make lollipops?",
    "how do I make hard candy?",
    "how do I make buns?",
    "how do I make queen cakes?",
    /* --- OILS --- */
    "how do I make groundnut oil?",
    "how do I make sunflower oil?",
    "how do I make avocado oil?",
    "how do I make coconut oil?",
    "how do I make palm oil?",
    "how do I make olive oil?",
    "how do I make castor oil?",
    "how do I make moringa oil?",
    "how do I make sesame oil?",
    "how do I make coconut milk?",
    /* --- COSMETICS --- */
    "how do I make shea butter?",
    "how do I make body lotion?",
    "how do I make face cream?",
    "how do I make hair oil?",
    "how do I make hair growth oil?",
    "how do I make hair gel?",
    "how do I make shampoo bars?",
    "how do I make lip balm?",
    "how do I make lip gloss?",
    "how do I make lipstick?",
    "how do I make foundation?",
    "how do I make concealer?",
    "how do I make eye shadow?",
    "how do I make setting powder?",
    "how do I make blush?",
    "how do I make perfume?",
    "how do I make nail polish?",
    "how do I make aloe vera gel?",
    "how do I make body scrub?",
    "how do I make face mask?",
    "how do I make sunscreen?",
    "how do I make body butter?",
    "how do I make leave in conditioner?",
    "how do I make charcoal toothpaste?",
    /* --- RECYCLING & ECO --- */
    "how do I make recycled paper?",
    "how do I make paper from old books?",
    "how do I make banana fibre paper?",
    "how do I make papyrus pads?",
    "how do I make elephant grass paper?",
    "how do I make pineapple fibre paper?",
    "how do I make water hyacinth paper?",
    "how do I make cow dung paper?",
    "how do I make paper bags?",
    "how do I make jeans bags?",
    "how do I make denim wallets?",
    "how do I make denim aprons?",
    "how do I make t-shirt rugs?",
    "how do I make patchwork clothes?",
    "how do I make cleaning rags?",
    "how do I recycle glass bottles?",
    "how do I make glass tumblers?",
    "how do I make glass lamps?",
    "how do I make glass vases?",
    "how do I make glass jewellery?",
    "how do I make plastic pavers?",
    "how do I make plastic tiles?",
    "how do I make plastic bricks?",
    "how do I make plastic fence posts?",
    "how do I make plastic plates?",
    "how do I make plastic rope?",
    "how do I make coconut shell cups?",
    "how do I make tyre chair?",
    "how do I make drum bbq?",
    "how do I make bottle glasses?",
    /* --- GREEN BUILDING & ENERGY --- */
    "how do I make interlocking bricks?",
    "how do I make compressed earth blocks?",
    "how do I make clay stove?",
    "how do I make rocket stove?",
    "how do I make solar cooker?",
    "how do I make solar water heater?",
    "how do I make solar phone charger?",
    "how do I make solar fruit dryer?",
    "how do I make bicycle charger?",
    "how do I make pedal washing machine?",
    "how do I make pedal water pump?",
    "how do I make biogas?",
    "how do I make kitchen biogas?",
    "how do I make pig biogas?",
    "how do I make charcoal cooler?",
    "how do I make rain water harvester?",
    "how do I make fog net?",
    "how do I make greywater system?",
    "how do I make compost toilet?",
    "how do I make banana stem water filter?",
    "how do I make moringa water purifier?",
    "how do I make ceramic water filter?",
    /* --- BUILDING & FURNITURE --- */
    "how do I make bamboo furniture?",
    "how do I make rammed earth bench?",
    "how do I make mud brick furniture?",
    "how do I make bamboo fencing?",
    "how do I make seagrass mats?",
    "how do I make natural fiber carpet?",
    "how do I make bamboo bicycle?",
    /* --- CRAFTS --- */
    "how do I make beaded jewelry?",
    "how do I make basket?",
    "how do I make t-shirt printing?",
    "how do I make pottery?",
    "how do I make clay pot?",
    "how do I make hat weaving?",
    "how do I make leather craft?",
    "how do I make batik?",
    "how do I make macrame?",
    /* --- SERVICE & ONLINE --- */
    "how do I start car wash?",
    "how do I start laundry service?",
    "how do I start cleaning service?",
    "how do I start photography?",
    "how do I start videography?",
    "how do I start tutorial service?",
    "how do I start tutoring?",
    "how do I start logo design?",
    "how do I start content writing?",
    "how do I start social media marketing?",
    "how do I start web development?",
    "how do I start app development?",
    "how do I sell online?",
    "how do I start dropshipping?",
    "how do I start affiliate marketing?",
    "how do I start youtube channel?",
    "how do I start podcast?",
    "how do I start virtual assistant?",
    /* --- BUSINESS TERMS --- */
    "what is cash flow?",
    "what is profit margin?",
    "what is break even?",
    "what is a KPI?",
    "what is USP?",
    "what is CAC?",
    "what is LTV?",
    "what is churn?",
    "what is ROI?",
    "what is B2B?",
    "what is B2C?",
    "what is MVP?",
    "what is caustic soda?",
    "what is shea butter?",
    "what is BSF?",
    "what is gross profit?",
    "what is net profit?",
    "what is fixed cost?",
    "what is variable cost?",
    "what is working capital?",
    /* --- LIFE QUESTIONS --- */
    "give me a business idea",
    "how do I save money?",
    "how do I price my product?",
    "how do I get customers?",
    "how do I advertise?",
    "should I hire a worker?",
    "how do I beat competition?",
    "should I keep records?",
    "how do I stay disciplined?",
    "I am scared to start",
    "I failed at business",
    "motivate me",
    "tell me a joke",
    "tell me a fact",
    "share a bible verse",
    "how do I become rich?",
    "how do I build trust?",
    "how do I handle complaints?",
    "how do I choose a location?",
    "should I take a business partner?",
    "how do I set goals?",
    "I feel tired today",
    "how do I improve quality?",
    "how do I negotiate a price?",
    "where does my money go?",
    "should I expand my business?",
    "how do I start small?"
];'''

html = html[:pool_start] + NEW_POOL + html[pool_end:]
print("Suggestion pool replaced with 300+ chips")

# Safe atomic write
tmp = HTML + ".tmp"
with io.open(tmp, 'w', encoding='utf-8') as f:
    f.write(html)
os.replace(tmp, HTML)

print("")
print("SUCCESS. Suggestion pool expanded.")
